services:
  db:
    image: postgres:15.14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - app_data:/var/lib/postgresql/data

volumes:
  app_data:
